import datetime

def generate_sadeem_report(ncr_issues, savings):
    report_name = f"Sadeem_Design_Review_{datetime.date.today()}.txt"
    
    with open(report_name, "w", encoding="utf-8") as f:
        f.write("==========================================\n")
        f.write("      SADEEM AI: DESIGN REVIEW REPORT     \n")
        f.write(f"      Date: {datetime.date.today()}       \n")
        f.write("==========================================\n\n")
        
        f.write("1. ISSUE REGISTER (NCR LOG):\n")
        f.write("-" * 30 + "\n")
        for issue in ncr_issues:
            f.write(f"[{issue['Severity']}] {issue['Issue_ID']}: {issue['Description']}\n")
            f.write(f"Reference: {issue['Requirement']}\n\n")
        
        f.write("2. ECONOMIC IMPACT:\n")
        f.write("-" * 30 + "\n")
        f.write(f"Total Estimated Savings: {savings} SAR\n")
        f.write("Optimization Logic: Applied per SEC/SBC standards.\n\n")
        
        f.write("==========================================\n")
        f.write("Generated by: Sadeem AI Platform\n")
        f.write("Lead Developer: Rawan Abdulaziz Alsubhi\n")

    print(f"✅ Report generated successfully: {report_name}")

# دمج مخرجات المهام السابقة
ncr_data = [
    {"Issue_ID": "NCR-01", "Severity": "Critical", "Requirement": "SBC 401", "Description": "Voltage drop 4.2% exceeds 3%."},
    {"Issue_ID": "NCR-02", "Severity": "Major", "Requirement": "IEC 62548-1", "Description": "String Voc exceeds MPPT limit."}
]
generate_sadeem_report(ncr_data, 750.0)
